/**
 * Catalog API
 *
 * Methods for collecting product/sku catalog data, categories, brands and other information. <br><br> All content that comes between {{}} keys must be replaced with the correct data before performing the request. <br><br> Common parameters that must be changed in most VTEX requests <br> {{accountName}} => Store account name <br> {{environment}} => The environment that will be called. Change for vtexcommercestable or vtexcommmercebeta <br> {{X-VTEX-API-AppKey}} => Located in the headers of the requests, user authentication key <br> {{X-VTEX-API-AppToken}} => Located in the headers of the requests, authentication password
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Field

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param name 
 * @param propertyKeys 
 * @param fields 
 * @param isActive 
 * @param isRequired 
 */

data class Attachment (

    @Json(name = "Id")
    val id: kotlin.Int,

    @Json(name = "Name")
    val name: kotlin.String,

    @Json(name = "Keys")
    val propertyKeys: kotlin.collections.List<kotlin.String>,

    @Json(name = "Fields")
    val fields: kotlin.collections.List<Field>,

    @Json(name = "IsActive")
    val isActive: kotlin.Boolean,

    @Json(name = "IsRequired")
    val isRequired: kotlin.Boolean

)

