/**
 * Catalog API
 *
 * Methods for collecting product/sku catalog data, categories, brands and other information. <br><br> All content that comes between {{}} keys must be replaced with the correct data before performing the request. <br><br> Common parameters that must be changed in most VTEX requests <br> {{accountName}} => Store account name <br> {{environment}} => The environment that will be called. Change for vtexcommercestable or vtexcommmercebeta <br> {{X-VTEX-API-AppKey}} => Located in the headers of the requests, user authentication key <br> {{X-VTEX-API-AppToken}} => Located in the headers of the requests, authentication password
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param id Category ID.
 * @param name Category name.
 * @param fatherCategoryId ID of the father category, apply in case of category and subcategory.
 * @param title Category tag title.
 * @param description Describes details about the category.
 * @param keywords Substitutes words for the category.
 * @param isActive Shows if the category is active (`true`) or not (`false`).
 * @param lomadeeCampaignCode This is a legacy field. Do not take this information into consideration.
 * @param adWordsRemarketingCode This is a legacy field. Do not take this information into consideration.
 * @param showInStoreFront Shows if is on side and upper menu (`true`) or not (`false`).
 * @param showBrandFilter If category has brand filter (`true`) or not (`false`).
 * @param activeStoreFrontLink If the Category has an active link on the website (`true`) or not (`false`).
 * @param globalCategoryId Google Global Category ID.
 * @param stockKeepingUnitSelectionMode Shows how the SKU will be exhibit.
 * @param score Score for search ordination.
 * @param linkId Text Link.
 * @param hasChildren If the category has a category child (`true`) or not (`false`).
 */

data class InlineResponse20014 (

    /* Category ID. */
    @Json(name = "Id")
    val id: kotlin.Int? = null,

    /* Category name. */
    @Json(name = "Name")
    val name: kotlin.String? = null,

    /* ID of the father category, apply in case of category and subcategory. */
    @Json(name = "FatherCategoryId")
    val fatherCategoryId: kotlin.Int? = null,

    /* Category tag title. */
    @Json(name = "Title")
    val title: kotlin.String? = null,

    /* Describes details about the category. */
    @Json(name = "Description")
    val description: kotlin.String? = null,

    /* Substitutes words for the category. */
    @Json(name = "Keywords")
    val keywords: kotlin.String? = null,

    /* Shows if the category is active (`true`) or not (`false`). */
    @Json(name = "IsActive")
    val isActive: kotlin.Boolean? = null,

    /* This is a legacy field. Do not take this information into consideration. */
    @Json(name = "LomadeeCampaignCode")
    val lomadeeCampaignCode: kotlin.String? = null,

    /* This is a legacy field. Do not take this information into consideration. */
    @Json(name = "AdWordsRemarketingCode")
    val adWordsRemarketingCode: kotlin.String? = null,

    /* Shows if is on side and upper menu (`true`) or not (`false`). */
    @Json(name = "ShowInStoreFront")
    val showInStoreFront: kotlin.Boolean? = null,

    /* If category has brand filter (`true`) or not (`false`). */
    @Json(name = "ShowBrandFilter")
    val showBrandFilter: kotlin.Boolean? = null,

    /* If the Category has an active link on the website (`true`) or not (`false`). */
    @Json(name = "ActiveStoreFrontLink")
    val activeStoreFrontLink: kotlin.Boolean? = null,

    /* Google Global Category ID. */
    @Json(name = "GlobalCategoryId")
    val globalCategoryId: kotlin.Int? = null,

    /* Shows how the SKU will be exhibit. */
    @Json(name = "StockKeepingUnitSelectionMode")
    val stockKeepingUnitSelectionMode: kotlin.String? = null,

    /* Score for search ordination. */
    @Json(name = "Score")
    val score: kotlin.Int? = null,

    /* Text Link. */
    @Json(name = "LinkId")
    val linkId: kotlin.String? = null,

    /* If the category has a category child (`true`) or not (`false`). */
    @Json(name = "HasChildren")
    val hasChildren: kotlin.Boolean? = null

)

