/**
 * Catalog API
 *
 * Methods for collecting product/sku catalog data, categories, brands and other information. <br><br> All content that comes between {{}} keys must be replaced with the correct data before performing the request. <br><br> Common parameters that must be changed in most VTEX requests <br> {{accountName}} => Store account name <br> {{environment}} => The environment that will be called. Change for vtexcommercestable or vtexcommmercebeta <br> {{X-VTEX-API-AppKey}} => Located in the headers of the requests, user authentication key <br> {{X-VTEX-API-AppToken}} => Located in the headers of the requests, authentication password
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param id ID of the Product.
 * @param name Name of the Product.
 * @param departmentId ID of product department.
 * @param categoryId ID of product Category.
 * @param brandId ID of the product Brand.
 * @param linkId Category URL.
 * @param refId Product Reference ID.
 * @param isVisible If the product are visible in search and list pages.
 * @param description Product Description, HTML is allowed.
 * @param descriptionShort Product Short Description.
 * @param releaseDate Product Release Date, for list ordering and product cluster highlight.
 * @param keyWords Alternatives Keywords to improve the product findability.
 * @param title Meta Title for the Product page.
 * @param isActive If the product is Active.
 * @param taxCode SKU Tax Code.
 * @param metaTagDescription Meta Description for the Product page.
 * @param supplierId Product Supplier ID.
 * @param showWithoutStock If the product can be visible without stock.
 * @param listStoreId Array with the ID of all the trade policies that are related to the product.
 * @param adWordsRemarketingCode This is a legacy field. Do not take this information into consideration.
 * @param lomadeeCampaignCode This is a legacy field. Do not take this information into consideration.
 */

data class InlineResponse2004 (

    /* ID of the Product. */
    @Json(name = "Id")
    val id: kotlin.Int? = null,

    /* Name of the Product. */
    @Json(name = "Name")
    val name: kotlin.String? = null,

    /* ID of product department. */
    @Json(name = "DepartmentId")
    val departmentId: kotlin.Int? = null,

    /* ID of product Category. */
    @Json(name = "CategoryId")
    val categoryId: kotlin.Int? = null,

    /* ID of the product Brand. */
    @Json(name = "BrandId")
    val brandId: kotlin.Int? = null,

    /* Category URL. */
    @Json(name = "LinkId")
    val linkId: kotlin.String? = null,

    /* Product Reference ID. */
    @Json(name = "RefId")
    val refId: kotlin.String? = null,

    /* If the product are visible in search and list pages. */
    @Json(name = "IsVisible")
    val isVisible: kotlin.Boolean? = null,

    /* Product Description, HTML is allowed. */
    @Json(name = "Description")
    val description: kotlin.String? = null,

    /* Product Short Description. */
    @Json(name = "DescriptionShort")
    val descriptionShort: kotlin.String? = null,

    /* Product Release Date, for list ordering and product cluster highlight. */
    @Json(name = "ReleaseDate")
    val releaseDate: kotlin.String? = null,

    /* Alternatives Keywords to improve the product findability. */
    @Json(name = "KeyWords")
    val keyWords: kotlin.String? = null,

    /* Meta Title for the Product page. */
    @Json(name = "Title")
    val title: kotlin.String? = null,

    /* If the product is Active. */
    @Json(name = "IsActive")
    val isActive: kotlin.Boolean? = null,

    /* SKU Tax Code. */
    @Json(name = "TaxCode")
    val taxCode: kotlin.String? = null,

    /* Meta Description for the Product page. */
    @Json(name = "MetaTagDescription")
    val metaTagDescription: kotlin.String? = null,

    /* Product Supplier ID. */
    @Json(name = "SupplierId")
    val supplierId: kotlin.Int? = null,

    /* If the product can be visible without stock. */
    @Json(name = "ShowWithoutStock")
    val showWithoutStock: kotlin.Boolean? = null,

    /* Array with the ID of all the trade policies that are related to the product. */
    @Json(name = "ListStoreId")
    val listStoreId: kotlin.collections.List<kotlin.Int>? = null,

    /* This is a legacy field. Do not take this information into consideration. */
    @Json(name = "AdWordsRemarketingCode")
    val adWordsRemarketingCode: kotlin.String? = null,

    /* This is a legacy field. Do not take this information into consideration. */
    @Json(name = "LomadeeCampaignCode")
    val lomadeeCampaignCode: kotlin.String? = null

)

