/**
 * Catalog API
 *
 * Methods for collecting product/sku catalog data, categories, brands and other information. <br><br> All content that comes between {{}} keys must be replaced with the correct data before performing the request. <br><br> Common parameters that must be changed in most VTEX requests <br> {{accountName}} => Store account name <br> {{environment}} => The environment that will be called. Change for vtexcommercestable or vtexcommmercebeta <br> {{X-VTEX-API-AppKey}} => Located in the headers of the requests, user authentication key <br> {{X-VTEX-API-AppToken}} => Located in the headers of the requests, authentication password
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * An array with all brands of the store.
 *
 * @param id Brand ID.
 * @param name Brand name.
 * @param isActive If the brand is active (`true`) or not (`false`).
 * @param title Brand title tag.
 * @param metaTagDescription A brief description of the brand.
 * @param imageUrl URL of the brand's image.
 */

data class InlineResponse20015 (

    /* Brand ID. */
    @Json(name = "id")
    val id: kotlin.Int? = null,

    /* Brand name. */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* If the brand is active (`true`) or not (`false`). */
    @Json(name = "isActive")
    val isActive: kotlin.Boolean? = null,

    /* Brand title tag. */
    @Json(name = "title")
    val title: kotlin.String? = null,

    /* A brief description of the brand. */
    @Json(name = "metaTagDescription")
    val metaTagDescription: kotlin.String? = null,

    /* URL of the brand's image. */
    @Json(name = "imageUrl")
    val imageUrl: kotlin.String? = null

)

