/**
 * Catalog API
 *
 * Methods for collecting product/sku catalog data, categories, brands and other information. <br><br> All content that comes between {{}} keys must be replaced with the correct data before performing the request. <br><br> Common parameters that must be changed in most VTEX requests <br> {{accountName}} => Store account name <br> {{environment}} => The environment that will be called. Change for vtexcommercestable or vtexcommmercebeta <br> {{X-VTEX-API-AppKey}} => Located in the headers of the requests, user authentication key <br> {{X-VTEX-API-AppToken}} => Located in the headers of the requests, authentication password
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param skuId SKU ID.
 * @param position SKU position.
 * @param subCollectionId Subcollection ID.
 */

data class InlineObject15 (

    /* SKU ID. */
    @Json(name = "skuId")
    val skuId: kotlin.Int = 1,

    /* SKU position. */
    @Json(name = "position")
    val position: kotlin.Int = 1,

    /* Subcollection ID. */
    @Json(name = "subCollectionId")
    val subCollectionId: kotlin.Int = 17

)

