/**
 * Catalog API
 *
 * Methods for collecting product/sku catalog data, categories, brands and other information. <br><br> All content that comes between {{}} keys must be replaced with the correct data before performing the request. <br><br> Common parameters that must be changed in most VTEX requests <br> {{accountName}} => Store account name <br> {{environment}} => The environment that will be called. Change for vtexcommercestable or vtexcommmercebeta <br> {{X-VTEX-API-AppKey}} => Located in the headers of the requests, user authentication key <br> {{X-VTEX-API-AppToken}} => Located in the headers of the requests, authentication password
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * Object with information of the specification.
 *
 * @param id ID of the association of the Product and the specification.
 * @param productId Product ID.
 * @param fieldId Specification ID.
 * @param fieldValueId Current specification value ID.
 * @param text Current specification value text.
 */

data class InlineResponse2007 (

    /* ID of the association of the Product and the specification. */
    @Json(name = "Id")
    val id: kotlin.Int? = null,

    /* Product ID. */
    @Json(name = "ProductId")
    val productId: kotlin.Int? = null,

    /* Specification ID. */
    @Json(name = "FieldId")
    val fieldId: kotlin.Int? = null,

    /* Current specification value ID. */
    @Json(name = "FieldValueId")
    val fieldValueId: kotlin.Int? = null,

    /* Current specification value text. */
    @Json(name = "Text")
    val text: kotlin.String? = null

)

