/**
 * Catalog API
 *
 * Methods for collecting product/sku catalog data, categories, brands and other information. <br><br> All content that comes between {{}} keys must be replaced with the correct data before performing the request. <br><br> Common parameters that must be changed in most VTEX requests <br> {{accountName}} => Store account name <br> {{environment}} => The environment that will be called. Change for vtexcommercestable or vtexcommmercebeta <br> {{X-VTEX-API-AppKey}} => Located in the headers of the requests, user authentication key <br> {{X-VTEX-API-AppToken}} => Located in the headers of the requests, authentication password
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * Object with information about the product and SKUs list.
 *
 * @param total Total quantity of SKUs.
 * @param from Initial product ID.
 * @param to Final product ID.
 */

data class InlineResponse200Range (

    /* Total quantity of SKUs. */
    @Json(name = "total")
    val total: kotlin.Int? = null,

    /* Initial product ID. */
    @Json(name = "from")
    val from: kotlin.Int? = null,

    /* Final product ID. */
    @Json(name = "to")
    val to: kotlin.Int? = null

)

