/**
 * Catalog API
 *
 * Methods for collecting product/sku catalog data, categories, brands and other information. <br><br> All content that comes between {{}} keys must be replaced with the correct data before performing the request. <br><br> Common parameters that must be changed in most VTEX requests <br> {{accountName}} => Store account name <br> {{environment}} => The environment that will be called. Change for vtexcommercestable or vtexcommmercebeta <br> {{X-VTEX-API-AppKey}} => Located in the headers of the requests, user authentication key <br> {{X-VTEX-API-AppToken}} => Located in the headers of the requests, authentication password
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param id Brand’s numerical identifier.
 * @param name Brand’s name.
 * @param text Brand’s description.
 * @param keywords Substitutes words for the Brand.
 * @param siteTitle Brand’s page title.
 * @param active If the Brand is active.
 * @param menuHome If the Brand shows on the home menu or not.
 * @param adWordsRemarketingCode This is a legacy field. Do not take this information into consideration.
 * @param lomadeeCampaignCode This is a legacy field. Do not take this information into consideration.
 * @param score Score for search ordination.
 * @param linkId Brand’s link ID.
 */

data class InlineResponse20017 (

    /* Brand’s numerical identifier. */
    @Json(name = "Id")
    val id: kotlin.Int? = null,

    /* Brand’s name. */
    @Json(name = "Name")
    val name: kotlin.String? = null,

    /* Brand’s description. */
    @Json(name = "Text")
    val text: kotlin.String? = null,

    /* Substitutes words for the Brand. */
    @Json(name = "Keywords")
    val keywords: kotlin.String? = null,

    /* Brand’s page title. */
    @Json(name = "SiteTitle")
    val siteTitle: kotlin.String? = null,

    /* If the Brand is active. */
    @Json(name = "Active")
    val active: kotlin.Boolean? = null,

    /* If the Brand shows on the home menu or not. */
    @Json(name = "MenuHome")
    val menuHome: kotlin.Boolean? = null,

    /* This is a legacy field. Do not take this information into consideration. */
    @Json(name = "AdWordsRemarketingCode")
    val adWordsRemarketingCode: kotlin.String? = null,

    /* This is a legacy field. Do not take this information into consideration. */
    @Json(name = "LomadeeCampaignCode")
    val lomadeeCampaignCode: kotlin.String? = null,

    /* Score for search ordination. */
    @Json(name = "Score")
    val score: kotlin.String? = null,

    /* Brand’s link ID. */
    @Json(name = "LinkId")
    val linkId: kotlin.String? = null

)

