/**
 * Catalog API
 *
 * Methods for collecting product/sku catalog data, categories, brands and other information. <br><br> All content that comes between {{}} keys must be replaced with the correct data before performing the request. <br><br> Common parameters that must be changed in most VTEX requests <br> {{accountName}} => Store account name <br> {{environment}} => The environment that will be called. Change for vtexcommercestable or vtexcommmercebeta <br> {{X-VTEX-API-AppKey}} => Located in the headers of the requests, user authentication key <br> {{X-VTEX-API-AppToken}} => Located in the headers of the requests, authentication password
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param id SubCollection ID.
 * @param collectionId Collection ID.
 * @param name SubCollection Name.
 * @param type Either `“Exclusive”` (all the products contained in it will not be used) or `“Inclusive”` (all the products contained in it will be used).
 * @param preSale Defines if the collection is on PreSale.
 * @param release Defines if the collection is a new released one.
 */

data class InlineResponse20018 (

    /* SubCollection ID. */
    @Json(name = "Id")
    val id: kotlin.Int? = null,

    /* Collection ID. */
    @Json(name = "CollectionId")
    val collectionId: kotlin.Int? = null,

    /* SubCollection Name. */
    @Json(name = "Name")
    val name: kotlin.String? = null,

    /* Either `“Exclusive”` (all the products contained in it will not be used) or `“Inclusive”` (all the products contained in it will be used). */
    @Json(name = "Type")
    val type: kotlin.String? = null,

    /* Defines if the collection is on PreSale. */
    @Json(name = "PreSale")
    val preSale: kotlin.Boolean? = null,

    /* Defines if the collection is a new released one. */
    @Json(name = "Release")
    val release: kotlin.Boolean? = null

)

