/**
 * Catalog API
 *
 * Methods for collecting product/sku catalog data, categories, brands and other information. <br><br> All content that comes between {{}} keys must be replaced with the correct data before performing the request. <br><br> Common parameters that must be changed in most VTEX requests <br> {{accountName}} => Store account name <br> {{environment}} => The environment that will be called. Change for vtexcommercestable or vtexcommmercebeta <br> {{X-VTEX-API-AppKey}} => Located in the headers of the requests, user authentication key <br> {{X-VTEX-API-AppToken}} => Located in the headers of the requests, authentication password
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param skuServiceTypeId SKU Service Type ID
 * @param skuServiceValueId SKU Service Value ID
 * @param skuId SKU ID
 * @param name SKU Service Name. Maximum of 50 characters
 * @param text Internal description for the SKU Service. Maximum of 100 characters
 * @param isActive If the SKU Service is active or not
 */

data class RequestBody6 (

    /* SKU Service Type ID */
    @Json(name = "SkuServiceTypeId")
    val skuServiceTypeId: kotlin.Int = 2,

    /* SKU Service Value ID */
    @Json(name = "SkuServiceValueId")
    val skuServiceValueId: kotlin.Int = 1,

    /* SKU ID */
    @Json(name = "SkuId")
    val skuId: kotlin.Int = 1,

    /* SKU Service Name. Maximum of 50 characters */
    @Json(name = "Name")
    val name: kotlin.String = "Test name",

    /* Internal description for the SKU Service. Maximum of 100 characters */
    @Json(name = "Text")
    val text: kotlin.String = "Text",

    /* If the SKU Service is active or not */
    @Json(name = "IsActive")
    val isActive: kotlin.Boolean = true

)

