/**
 * Catalog API
 *
 * Methods for collecting product/sku catalog data, categories, brands and other information. <br><br> All content that comes between {{}} keys must be replaced with the correct data before performing the request. <br><br> Common parameters that must be changed in most VTEX requests <br> {{accountName}} => Store account name <br> {{environment}} => The environment that will be called. Change for vtexcommercestable or vtexcommmercebeta <br> {{X-VTEX-API-AppKey}} => Located in the headers of the requests, user authentication key <br> {{X-VTEX-API-AppToken}} => Located in the headers of the requests, authentication password
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param name Collection's Name
 * @param description Collection's description for internal use, with the collection's details. It will not be used for search engines
 * @param searchable Option making the collection searchable in the store
 * @param highlight Option if you want the collection to highlight specific products using a tag
 * @param dateFrom Collection start date and time. If a future date and time are set, the collection will have a scheduled status
 * @param dateTo Collection end date and time
 */

data class RequestBody15 (

    /* Collection's Name */
    @Json(name = "Name")
    val name: kotlin.String = "Halloween costumes",

    /* Collection's description for internal use, with the collection's details. It will not be used for search engines */
    @Json(name = "Description")
    val description: kotlin.String = "HomeHalloween",

    /* Option making the collection searchable in the store */
    @Json(name = "Searchable")
    val searchable: kotlin.Boolean = false,

    /* Option if you want the collection to highlight specific products using a tag */
    @Json(name = "Highlight")
    val highlight: kotlin.Boolean = false,

    /* Collection start date and time. If a future date and time are set, the collection will have a scheduled status */
    @Json(name = "DateFrom")
    val dateFrom: kotlin.String = "2020-11-26T15:23:00",

    /* Collection end date and time */
    @Json(name = "DateTo")
    val dateTo: kotlin.String = "2069-11-26T15:23:00"

)

