/**
 * Catalog API
 *
 * Methods for collecting product/sku catalog data, categories, brands and other information. <br><br> All content that comes between {{}} keys must be replaced with the correct data before performing the request. <br><br> Common parameters that must be changed in most VTEX requests <br> {{accountName}} => Store account name <br> {{environment}} => The environment that will be called. Change for vtexcommercestable or vtexcommmercebeta <br> {{X-VTEX-API-AppKey}} => Located in the headers of the requests, user authentication key <br> {{X-VTEX-API-AppToken}} => Located in the headers of the requests, authentication password
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param id Specification and SKU association unique identifier. This field cannot be updated
 * @param fieldId Specification unique identifier. This field cannot be updated
 * @param fieldValueId Specification value unique identifier. This field can only be updated with other values of the same `FieldId`
 * @param skuId SKU unique identifier. This field cannot be updated
 * @param text Specification Value Name. This field is automatically updated if the `FieldValue` is updated. Otherwise, the value cannot be modified
 */

data class RequestBody (

    /* Specification and SKU association unique identifier. This field cannot be updated */
    @Json(name = "Id")
    val id: kotlin.Int = 65,

    /* Specification unique identifier. This field cannot be updated */
    @Json(name = "FieldId")
    val fieldId: kotlin.Int = 32,

    /* Specification value unique identifier. This field can only be updated with other values of the same `FieldId` */
    @Json(name = "FieldValueId")
    val fieldValueId: kotlin.Int = 131,

    /* SKU unique identifier. This field cannot be updated */
    @Json(name = "SkuId")
    val skuId: kotlin.Int? = 21,

    /* Specification Value Name. This field is automatically updated if the `FieldValue` is updated. Otherwise, the value cannot be modified */
    @Json(name = "Text")
    val text: kotlin.String? = "Red"

)

